#%RAML 1.0 ResourceType
get:
  description: Retrieve a single <<type>>
  responses:
    200:
      description: Successfully retrieved <<type>>
      body:
        application/json:
          type: object
          properties:
            meta: object
            data:
              type: <<type>>
              example: <<example>>
    400:
      body:
        application/json:
          example: !include ../examples/status/Status400.raml
    404:
      body:
        application/json:
          example: !include ../examples/status/Status404.raml
    500:
      body:
        application/json:
          example: !include ../examples/status/Status500.raml
delete?:
  description: Delete an existing <<type>>
  responses:
    200:
      description: Successfully deleted <<type>>
      body:
        application/json:
          type: object
          properties:
            meta:
              type: object
              example:
                message: Successfully deleted <<type>>
            data: object
    400:
      body:
        application/json:
          example: !include ../examples/status/Status400.raml
    404:
      body:
        application/json:
          example: !include ../examples/status/Status404.raml
    500:
      body:
        application/json:
          example: !include ../examples/status/Status500.raml
put?:
  description: Update an existing <<type>>
  body:
    application/json:
      type: <<type>>
      example: <<example>>
  responses:
    200:
      description: Successfully updated <<type>>
      body:
        application/json:
          type: object
          properties:
            meta: object
            data:
              type: <<type>>
              example: <<example>>
    400:
      body:
        application/json:
          example: !include ../examples/status/Status400.raml
    404:
      body:
        application/json:
          example: !include ../examples/status/Status404.raml
    500:
      body:
        application/json:
          example: !include ../examples/status/Status500.raml