#%RAML 1.0 ResourceType
post?:
  description: Post a <<type>>
  body:
    application/json:
      type: <<type>>
      example: <<postExample>>
  responses:
    201:
      description: Successfully posted <<type>>
      body:
        application/json:
          type:  !include ../../types/WinResponse.raml
          example: <<example>>
    400:
      body:
        application/json:
          example:
            message: Invalid Input
    500:
      body:
        application/json:
          example:
            message: Internal Server Error