#%RAML 1.0 ResourceType
get?:
  description: Retrieve a single <<type>>
  responses:
    200:
      description: Successfully retrieved <<type>>
      body:
        application/json:
          type: object
          examples: <<singletonExample>>
    400:
      body:
        application/json:
          type: object
          example:
            message: Invalid Input
    404:
      body:
        application/json:
          type: object
          example:
            message: Not Found
    500:
      body:
        application/json:
          type: object
          example:
            message: Internal Server Error
delete?:
  description: Delete an existing <<type>>
  responses:
    200:
      description: Successfully deleted <<type>>
      body:
        application/json:
          type: object
          example:
            meta:
              message: Successfully deleted <<type>>
            data: {}
    400:
      body:
        application/json:
          type: object
          example:
            message: Invalid Input
    404:
      body:
        application/json:
          type: object
          example:
            message: Not Found
    500:
      body:
        application/json:
          type: object
          example:
            message: Internal Server Error
put?:
  description: Update an existing <<type>>
  body:
    application/json:
      type: <<type>>
      examples: <<putExample>>
  responses:
    200:
      description: Successfully updated <<type>>
      body:
        application/json:
          type: object
          examples: <<singletonExample>>
    400:
      body:
        application/json:
          type: object
          example:
            message: Invalid Input
    404:
      body:
        application/json:
          type: object
          example:
            message: Not Found
    500:
      body:
        application/json:
          type: object
          example:
            message: Internal Server Error