#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example:
          message: Invalid Input
  404:
    body:
      application/json:
        example:
          message: Not Found
  500:
    body:
      application/json:
        example:
          message: Internal Server Error