#%RAML 1.0 Trait
queryParameters:
  page:
    description: Current page
    type: number
    required: false
    example: 0
    default: 0
  rpp:
    description: Number of results per page
    type: number
    required: false
    example: 25
    default: 25